### ISSUE TITLE
No click events and hover events on 1.18!

### ISSUE THREAD

**Issue by MultiChipModule** [NicoNekoDev/AstralBooks#41] opened 2021-12-13 23:24 UTC
When using the plugin with clickable text in my books, nothing happens.
Hovering when using the hover event also does nothing. Holding the original book has both of these working.

**Comment by NicoNekoDev** [comment] 2021-12-14 10:40
The issue is with PlaceholderAPI. It will be fixed in the next update (probably tomorrow).

**Closed as completed** 2021-12-15 10:31 UTC
